# Final Project


## What is it?

In this class, you are expected to work in a group, with classmates,
to complete a small data analysis project using what you learn from the
class (and beyond) about **R**.  Your group should enerate a analysis report, and present it in the last week.


## What are the project options?

You can work on almost anything you want. Ideally, the projects will be based on *real* data analysis tasks you have from your research or daily work. We can help you find suitable data sources if you do not have data in hand. A couple of options from previous offerings of the course are described below, as well. 

As illustrated in the moviestar example below, the project doesn't need to be large or complicated. We expect you to demonstrate comfort with a range of **R** skills rather than mastery of any specific task.  Accordingly, projects should include all the following steps:

- Data Import
- Perform some exploration prior to analysis to make sure you understand the data and its ready to go. Depending on project this might include:

  - visualizations
    - summary statistics
    - data cleaning, such as standardizing terminology, removing samples with incomplete data, or applying a log transformation.

- Plan and perform an analysis. Its a good idea to keep the analysis itself simple so you can focus on your R skills rather than learning statistics. So be sure to try things out:

    - write at least one function of your own
    - use one or more programming routines such as *if-then* or *for loop*
    - try out *apply* or *sapply*

- Presentation of results in figures, tables, etc... 


## What needs to be in the report?

The report should include the following sections:

-   Background
    -   Introduction of the project
-   Goal
    -   Research question(s) the analysis aims to answer
-   Data
    -   Description of the data
    -   Data cleaning and manipulation steps
    -   Data summary and visualization
-   Analysis
    -   Methods applied in the analysis
-   Results and summary
    -   Report your findings


## How should the report be formatted?

-   Use **R Markdown** for conducting your analysis and generating the report.
-   You report may be included in this **R for Cancer Research** book!
-   An example is provided in the next chapter


## Recommendations

-   Try things out in R
    -   You should make a real effort to practice what was covered in class
        in a complete project that includes reading in data, doing something
        intentional to it and reporting the results of that analysis in an
        organized way.
-   Write up your methods and results
    -   Your project should demonstrate the principles of *literate coding*, meaning that the logic of the code, and reasons behind choices you made, are clearly explained in the report.  Likewise, results should be presented in a
        logical and readable way. Plots should have meaningful labels, and
        should incorporate such elements as color, multiple plotting symbols,
        and legends as necessary for clarity. Summary statistics should be
        rounded to a relevant number of significant digits, etc. Since this is a programming class, such formatting should be handled in the code, as much as possible, rather than tweaked manually. 
-   Submit clean, well commented code
    -   Code should employ self-documenting
        variable names, and include comments as needed so that a collaborator
        could follow it easily.
-   Reproducibility
    -   This means that we, with the same files in an appropriately named
        directory, can reproduce your final results simply by rendering your
        R markdown file.
    -   You will find it easier to produce clean code if you designate a
        discrete work space for the project, and keep everything there,
        always work from a script you write rather than working interactively
        at the R-prompt, organize your code into logical sections, and
        annotate your code with comments so you can keep track of what each
        chunk is supposed to do.
