# Project Options


## The Movie Lens Data (Example)

Consider the movie example in the previous chapter and try to answer the
following questions:

-   Organizing
    -   After reading all 3 files into R, you will want to think about how you
        organize and store the data for analysis. Do your data objects all
        have useful row and column names so that you can easily map movies and
        users across all data sets? Do you like having the ratings data in a 3
        column format, would a matrix make more sense? Are you happy having
        everything in 3 separate files? The format used in the
        ratingsDataPlus.txt file, may make it easier to work with the data for
        some problems. There are trade-offs no matter how its done, though,
        combining the files may make it easier to write code for analyses, but
        it uses a lot of storage space - the ratingsPlus file alone is more
        than 3 times as large as the other 3 files combined.
-   Favorite Genre
    -   Write code to identify a user’s favorite/least favorite genre, based
        on ratings. Use loops or apply functions to apply your code to all
        users, and then determine if results differ by age or gender. Note
        that genres are not mutually exclusive, this may affect your analysis.
-   User Similarity
    -   To make personalized recommendations, movie recommendation engines
        start by matching each user to others in the database with similar
        taste. Come up with a scheme for measuring similarity of users and
        code it up. Calculate a matrix of similarity scores for all pairs of
        users. We can build on this code on the second lab to make user
        recommendations.
-   Who liked Star Wars?
    -   Having matched a new user to a similar cohort from the database, the
        recommendation engine has to use the cohort’s past ratings to predict
        which movies the new user will like. It should not be surprising that
        Star Wars’ with 583 ratings, is the most watched movie in the
        database. Not everyone liked it though, write code to predict whether
        a user will like Star Wars, and apply it to all users. Apply the same
        approach to both Return of the Jedi and another, non-Star Wars movie,
        like George of the Jungle. Which predictions are closest to those for
        Star Wars?


## Todd Golub's Study

-   Background

    In 1999, Todd Golub and collaborators at the Whitehead Institute
    published this paper in Science. *Molecular Classification of Cancer: Class
    Discovery and Class Prediction by Gene Expression Monitoring T. R. Golub, et al.
    Science 286, 531 (1999); DOI: 10.1126/sci- ence.286.5439.531.*

    This study has
    become one of the milestones in the history of gene expression microarrays,
    instrumental in establishing that microarray arrays are reliable enough to be
    used for such complex tasks as tumor class discovery, and prediction. The
    accompanying data files contain a slightly modified version of the original
    study data.

    We have reduced the number of genes to speed up computation, and
    removed redundant probes so that each gene is only measured once. We have also
    messed with the original sample names so that the project can include the kinds
    of data grooming tasks that research datasets often require before they can be
    analyzed.

-   Goal

    Among the gene specific results reported in the Science paper, were
    findings that Cyclin D3 (CCND3) was more expressed in ALL whereas CD33
    was more highly expressed in AML?

    -   Identify these genes in the expression data and try to verify the finding
        by performing t-tests on them. This will require getting the AML-ALL
        designations from the clinical data file.
